name: deploy to ec2
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Debug SSH Key
        run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH Connection Successful'"

      - name: deploy via ssh
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./api/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/api/
            cd /home/ubuntu/api
            npm install
            
            if pm2 list | grep -q 'api'; then
               pm2 restart api
            else
               pm2 start npm --name "api" -- start
            fi
            pm2 save
